const GameData = [
    {
        date: '2022-03-20T21:00-06:00',
        homeTeam: "Royals",
        awayTeam: "Cardinals",
        homeSP: "Singer",
        awaySP: "Wainwright",
        prediction: 0,
    },
    {
        date: '2022-03-21T21:00-06:00',
        homeTeam: "Cardinals",
        awayTeam: "Royals",
        homeSP: "Wainwright",
        awaySP: "Singer",
        prediction: 1,
    },
    {
        date: '2022-03-21T21:00-06:00',
        homeTeam: "Cardinals",
        awayTeam: "Royals",
        homeSP: "Wainwright",
        awaySP: "Singer",
        prediction: 0,
    },
    {
        date: '2022-03-21T21:00-06:00',
        homeTeam: "Cardinals",
        awayTeam: "Royals",
        homeSP: "Wainwright",
        awaySP: "Singer",
        prediction: 1,
    },
    {
        date: '2022-03-21T21:00-06:00',
        homeTeam: "Cardinals",
        awayTeam: "Royals",
        homeSP: "Wainwright",
        awaySP: "Singer",
        prediction: 0,
    },
    {
        date: '2022-03-21T21:00-06:00',
        homeTeam: "Cardinals",
        awayTeam: "Royals",
        homeSP: "Wainwright",
        awaySP: "Singer",
        prediction: 1,
    },
    {
        date: '2022-03-21T21:00-06:00',
        homeTeam: "Cardinals",
        awayTeam: "Royals",
        homeSP: "Wainwright",
        awaySP: "Singer",
        prediction: 0,
    },
    {
        date: '2022-03-22T21:00-06:00',
        homeTeam: "Angels",
        awayTeam: "Dodgers",
        homeSP: "Ohtani",
        awaySP: "Scherzer",
        prediction: 1,
    },
    {
        date: '2022-03-23T21:00-06:00',
        homeTeam: "Dodgers",
        awayTeam: "Angels",
        homeSP: "Scherzer",
        awaySP: "Ohtani",
        prediction: 0,
    },
];

export default GameData;